const fs = require('fs');
const path = require('path');

let content = fs.readFileSync('./components/apps/SAP.tsx', 'utf8');

content = content.replace(/bg-\[\#EAF0F6\]/g, 'bg-black');
content = content.replace(/text-\[\#333\]/g, 'text-slate-300');
content = content.replace(/from-\[\#F7F9FB\]/g, 'from-white/10');
content = content.replace(/to-\[\#DEE5F0\]/g, 'to-white/5');
content = content.replace(/border-\[\#A3B0C5\]/g, 'border-white/10');
content = content.replace(/text-\[\#444\]/g, 'text-zinc-400');
content = content.replace(/hover:bg-blue-100/g, 'hover:bg-white/10');
content = content.replace(/border-\[\#BDC7D6\]/g, 'border-white/10');
content = content.replace(/bg-white/g, 'bg-zinc-900');
content = content.replace(/border-\[\#ABADB3\]/g, 'border-white/20');
content = content.replace(/text-green-600/g, 'text-emerald-400');
content = content.replace(/text-gray-500/g, 'text-zinc-500');
content = content.replace(/text-blue-600/g, 'text-blue-400');
content = content.replace(/text-\[\#666\]/g, 'text-zinc-400');
content = content.replace(/from-\[\#E1E9F4\]/g, 'from-white/10');
content = content.replace(/to-\[\#C9D6E9\]/g, 'to-white/5');
content = content.replace(/border-\[\#99A8BF\]/g, 'border-white/10');
content = content.replace(/bg-yellow-500\/20/g, 'bg-amber-500/20');
content = content.replace(/border-yellow-600/g, 'border-amber-500/30');
content = content.replace(/text-yellow-700/g, 'text-amber-400');
content = content.replace(/border-\[\#D0D9E5\]/g, 'border-white/10');
content = content.replace(/bg-\[\#F4F7FC\]/g, 'bg-zinc-950');
content = content.replace(/text-gray-600/g, 'text-zinc-400');
content = content.replace(/bg-\[\#EBEBE4\]/g, 'bg-zinc-900');
content = content.replace(/border-\[\#A0A0A0\]/g, 'border-white/20');
content = content.replace(/text-gray-700/g, 'text-slate-300');
content = content.replace(/bg-\[\#FFF\]/g, 'bg-black');
content = content.replace(/text-gray-800/g, 'text-white');
content = content.replace(/border-\[\#7F9DB9\]/g, 'border-white/20');
content = content.replace(/focus:bg-\[\#FEFFD6\]/g, 'focus:bg-white/10');
content = content.replace(/bg-\[\#EAF0F6\]\/30/g, 'bg-white/5');
content = content.replace(/hover:bg-\[\#D3E0F0\]/g, 'hover:bg-white/10');
content = content.replace(/hover:border-\[\#8EA6CE\]/g, 'hover:border-white/20');
content = content.replace(/active:bg-\[\#B4C7E3\]/g, 'active:bg-white/20');
content = content.replace(/text-\[\#555\]/g, 'text-zinc-400');
content = content.replace(/bg-\[\#F0F0F0\]/g, 'bg-white/5');
content = content.replace(/border-\[\#888\]/g, 'border-white/20');
content = content.replace(/hover:bg-\[\#E0E0E0\]/g, 'hover:bg-white/10');
content = content.replace(/text-\[\#000\]/g, 'text-white');
content = content.replace(/from-\[\#E8E8E8\]/g, 'from-white/5');
content = content.replace(/to-\[\#D0D0D0\]/g, 'to-transparent');
content = content.replace(/hover:from-\[\#F0F0F0\]/g, 'hover:from-white/10');
content = content.replace(/hover:to-\[\#E0E0E0\]/g, 'hover:to-white/5');
content = content.replace(/text-orange-600/g, 'text-amber-400');
content = content.replace(/border-\[\#B0B9C6\]/g, 'border-white/10');
content = content.replace(/from-\[\#D3E0F0\]/g, 'from-white/10');
content = content.replace(/to-\[\#EAF0F6\]/g, 'to-white/5');
content = content.replace(/text-\[\#334455\]/g, 'text-slate-200');
content = content.replace(/border-\[\#CAD5E2\]/g, 'border-white/10');

fs.writeFileSync('./components/apps/SAP.tsx', content, 'utf8');
console.log('Updated SAP.tsx');
